env:  
  OCTOPUS_PROJECT_NAME: Trident
  OCTOPUS_FEATURE_BRANCH_CHANNEL: Default
  OCTOPUS_FEATURE_BRANCH_ENVIRONMENT: Development
  OCTOPUS_RELEASE_CHANNEL: Release
  OCTOPUS_RELEASE_ENVIRONMENT: Staging  
  OCTOPUS_SPACE: Integration-Flyway
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUSSERVERAPIKEY }}
  OCTOPUS_URL: ${{ secrets.OCTOPUSSERVERURL }}